// Local type definitions (not in Prisma schema yet)
export enum EmailTemplateType {
  WELCOME = 'WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  VERIFICATION = 'VERIFICATION',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  NOTIFICATION = 'NOTIFICATION',
  COURSE_ENROLLMENT = 'COURSE_ENROLLMENT',
  WEEKLY_PROGRESS = 'WEEKLY_PROGRESS',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  NEW_COURSE_RECOMMENDATION = 'NEW_COURSE_RECOMMENDATION',
  BOOTCAMP_ANNOUNCEMENT = 'BOOTCAMP_ANNOUNCEMENT',
  INSTRUCTOR_BROADCAST = 'INSTRUCTOR_BROADCAST',
}

export enum EmailStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum ScheduledStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}
