import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import {
  Brain,
  Code,
  Users,
  Zap,
  Target,
  Trophy,
  Video,
  Terminal,
} from 'lucide-react'

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Roadmaps',
    description:
      'Get personalized learning paths generated by AI based on your goals and skill level.',
  },
  {
    icon: Code,
    title: 'Interactive Coding',
    description:
      'Practice with real-time code execution, test cases, and instant feedback.',
  },
  {
    icon: Video,
    title: 'Video Courses',
    description:
      'Learn from expert instructors with high-quality video content and DRM protection.',
  },
  {
    icon: Terminal,
    title: 'DevOps Scenarios',
    description:
      'Master Docker, Kubernetes, and cloud technologies with interactive terminal challenges.',
  },
  {
    icon: Users,
    title: 'Live Bootcamps',
    description:
      'Join cohort-based learning programs with live sessions and 1:1 mentorship.',
  },
  {
    icon: Target,
    title: 'DSA Practice',
    description:
      'Solve 1000+ coding problems with company-specific tags and spaced repetition.',
  },
  {
    icon: Zap,
    title: 'Real-time Feedback',
    description:
      'Get instant AI-powered hints and explanations when you are stuck.',
  },
  {
    icon: Trophy,
    title: 'Gamification',
    description:
      'Earn achievements, maintain streaks, and track your progress with detailed analytics.',
  },
]

export function FeaturesSection() {
  return (
    <section className="container py-24">
      <div className="mx-auto max-w-2xl text-center">
        <h2 className="mb-4 text-3xl font-bold tracking-tight sm:text-4xl">
          Everything You Need to Excel
        </h2>
        <p className="text-lg text-muted-foreground">
          Comprehensive tools and features designed to accelerate your tech career.
        </p>
      </div>

      <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
        {features.map((feature) => (
          <Card key={feature.title} className="border-2">
            <CardHeader>
              <feature.icon className="mb-2 h-10 w-10 text-primary" />
              <CardTitle className="text-xl">{feature.title}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{feature.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  )
}
