-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- This migration file will be generated by Prisma
-- Run: pnpm db:migrate to generate and apply migrations
