import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { OpenAIService } from './openai.service';

@Injectable()
export class SEOService {
  private readonly logger = new Logger(SEOService.name);

  constructor(
    private prisma: PrismaService,
    private openaiService: OpenAIService,
  ) {}

  /**
   * Generate SEO metadata for a course
   */
  async generateCourseSEO(courseId: string) {
    const course = await this.prisma.course.findUnique({
      where: { id: courseId },
      include: {
        instructor: {
          select: {
            username: true,
          },
        },
        skills: {
          include: {
            skill: true,
          },
        },
      },
    });

    if (!course) {
      throw new Error('Course not found');
    }

    // Generate meta title (max 60 characters)
    const metaTitle = this.generateMetaTitle(course.title);

    // Generate meta description (max 160 characters)
    const metaDescription = this.generateMetaDescription(course.description || course.title);

    // Generate keywords
    const keywords = this.generateKeywords(course);

    // Generate Open Graph tags
    const ogTitle = course.title;
    const ogDescription = metaDescription;
    const ogImage = course.thumbnailUrl || '';

    // Generate structured data (JSON-LD)
    const structuredData = this.generateStructuredData(course);

    // Auto-generate AI-powered description if needed
    let autoGeneratedDesc = '';
    if (!course.longDescription) {
      try {
        autoGeneratedDesc = await this.openaiService.generateCourseDescription(
          course.title,
          course.description || '',
          course.skills.map((s) => s.skill.name),
        );
      } catch (error) {
        this.logger.error('Failed to generate AI description', error);
      }
    }

    // Upsert SEO record
    const seoData = await this.prisma.courseSEO.upsert({
      where: { courseId },
      create: {
        courseId,
        metaTitle,
        metaDescription,
        keywords,
        ogTitle,
        ogDescription,
        ogImage,
        twitterCard: 'summary_large_image',
        canonicalUrl: `https://yourplatform.com/courses/${course.slug}`,
        structuredData,
        autoGeneratedDesc,
      },
      update: {
        metaTitle,
        metaDescription,
        keywords,
        ogTitle,
        ogDescription,
        ogImage,
        structuredData,
        autoGeneratedDesc: autoGeneratedDesc || undefined,
      },
    });

    this.logger.log(`SEO generated for course: ${courseId}`);

    return seoData;
  }

  /**
   * Generate meta title (optimized for SEO, max 60 chars)
   */
  private generateMetaTitle(title: string): string {
    const maxLength = 60;
    const suffix = ' | Learn Online';

    if (title.length + suffix.length <= maxLength) {
      return `${title}${suffix}`;
    }

    const truncatedTitle = title.substring(0, maxLength - suffix.length - 3) + '...';
    return truncatedTitle;
  }

  /**
   * Generate meta description (max 160 chars)
   */
  private generateMetaDescription(description: string): string {
    const maxLength = 160;

    if (description.length <= maxLength) {
      return description;
    }

    return description.substring(0, maxLength - 3) + '...';
  }

  /**
   * Generate keywords from course data
   */
  private generateKeywords(course: any): string[] {
    const keywords = [
      course.title,
      ...(course.skills?.map((s: any) => s.skill.name) || []),
      course.difficultyLevel,
      'online course',
      'learn online',
      'programming',
    ];

    return keywords.filter(Boolean).slice(0, 10); // Max 10 keywords
  }

  /**
   * Generate JSON-LD structured data
   */
  private generateStructuredData(course: any): any {
    return {
      '@context': 'https://schema.org',
      '@type': 'Course',
      name: course.title,
      description: course.description || course.title,
      provider: {
        '@type': 'Organization',
        name: 'Your Learning Platform',
        sameAs: 'https://yourplatform.com',
      },
      instructor: {
        '@type': 'Person',
        name: course.instructor.username,
      },
      offers: {
        '@type': 'Offer',
        category: 'Education',
        price: Number(course.price),
        priceCurrency: 'USD',
      },
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: Number(course.ratingAverage),
        ratingCount: course.ratingCount,
      },
      courseCode: course.slug,
      educationalLevel: course.difficultyLevel,
      inLanguage: course.language || 'en',
      thumbnailUrl: course.thumbnailUrl,
      hasCourseInstance: {
        '@type': 'CourseInstance',
        courseMode: 'online',
        courseWorkload: `PT${course.estimatedDurationHours || 0}H`,
      },
    };
  }

  /**
   * Get SEO data for a course
   */
  async getCourseSEO(courseId: string) {
    return this.prisma.courseSEO.findUnique({
      where: { courseId },
    });
  }

  /**
   * Update course SEO manually
   */
  async updateCourseSEO(courseId: string, seoData: any) {
    return this.prisma.courseSEO.update({
      where: { courseId },
      data: seoData,
    });
  }

  /**
   * Regenerate SEO for all published courses
   */
  async regenerateAllSEO() {
    const courses = await this.prisma.course.findMany({
      where: { isPublished: true },
    });

    const results = await Promise.allSettled(
      courses.map((course) => this.generateCourseSEO(course.id)),
    );

    const successful = results.filter((r) => r.status === 'fulfilled').length;
    const failed = results.filter((r) => r.status === 'rejected').length;

    this.logger.log(`SEO regeneration complete: ${successful} succeeded, ${failed} failed`);

    return {
      total: courses.length,
      successful,
      failed,
    };
  }
}
