import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma/prisma.service';
import { PdfGeneratorService } from './pdf-generator.service';

@Injectable()
export class CertificateService {
  constructor(
    private prisma: PrismaService,
    private pdfGenerator: PdfGeneratorService,
  ) {}

  /**
   * Generate certificate for bootcamp completion
   * Phase 6: Auto-generation on completion
   */
  async generateBootcampCertificate(enrollmentId: string) {
    const enrollment = await this.prisma.cohortEnrollment.findUnique({
      where: { id: enrollmentId },
      include: {
        user: {
          include: {
            profile: true,
          },
        },
        cohort: {
          include: {
            bootcamp: {
              include: {
                instructor: true,
              },
            },
          },
        },
      },
    });

    if (!enrollment) {
      throw new NotFoundException('Enrollment not found');
    }

    if (enrollment.enrollmentStatus !== 'completed') {
      throw new BadRequestException('Student has not completed the bootcamp');
    }

    // Check if certificate already exists
    const existing = await this.prisma.certificate.findFirst({
      where: {
        userId: enrollment.userId,
        certificateType: 'bootcamp',
        resourceId: enrollment.cohort.bootcampId,
      },
    });

    if (existing && !existing.isRevoked) {
      return existing;
    }

    // Get or create template
    let template = await this.prisma.certificateTemplate.findFirst({
      where: {
        bootcampId: enrollment.cohort.bootcampId,
        templateType: 'bootcamp_completion',
        isActive: true,
      },
    });

    if (!template) {
      template = await this.prisma.certificateTemplate.findFirst({
        where: {
          bootcampId: null,
          templateType: 'bootcamp_completion',
          isActive: true,
        },
      });
    }

    if (!template) {
      throw new NotFoundException('No certificate template available');
    }

    // Generate certificate data
    const certificateData = {
      recipientName: enrollment.user.profile?.fullName || enrollment.user.username,
      certificateTitle: enrollment.cohort.bootcamp.title,
      description: `Has successfully completed the ${enrollment.cohort.bootcamp.title} bootcamp`,
      issueDate: new Date(),
      metadata: {
        bootcampId: enrollment.cohort.bootcampId,
        cohortId: enrollment.cohortId,
        enrollmentId: enrollment.id,
        completionDate: enrollment.completedAt,
        finalGrade: enrollment.finalGrade,
        instructorName: enrollment.cohort.bootcamp.instructor.username,
      },
    };

    // Generate PDF
    const pdfUrl = await this.pdfGenerator.generateCertificatePdf(
      template,
      certificateData,
    );

    // Create certificate record
    const certificate = await this.prisma.certificate.create({
      data: {
        userId: enrollment.userId,
        templateId: template.id,
        certificateType: 'bootcamp',
        resourceId: enrollment.cohort.bootcampId,
        certificateNumber: '', // Auto-generated by trigger
        issueDate: certificateData.issueDate,
        recipientName: certificateData.recipientName,
        certificateTitle: certificateData.certificateTitle,
        description: certificateData.description,
        pdfUrl,
        verificationUrl: '', // Will be set after creation
        metadata: certificateData.metadata,
      },
    });

    // Update verification URL
    const verificationUrl = `${process.env.FRONTEND_URL}/certificates/verify/${certificate.certificateNumber}`;
    const linkedinShareUrl = `https://www.linkedin.com/profile/add?startTask=CERTIFICATION_NAME&name=${encodeURIComponent(certificateData.certificateTitle)}&organizationId=${process.env.ORGANIZATION_ID}&issueYear=${new Date().getFullYear()}&certUrl=${encodeURIComponent(verificationUrl)}`;

    await this.prisma.certificate.update({
      where: { id: certificate.id },
      data: {
        verificationUrl,
        linkedinShareUrl,
      },
    });

    // Update enrollment with certificate URL
    await this.prisma.cohortEnrollment.update({
      where: { id: enrollmentId },
      data: { certificateUrl: pdfUrl },
    });

    return this.findOne(certificate.id);
  }

  /**
   * Get certificate by ID
   */
  async findOne(id: string) {
    const certificate = await this.prisma.certificate.findUnique({
      where: { id },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            email: true,
            profilePictureUrl: true,
            profile: true,
          },
        },
        template: true,
      },
    });

    if (!certificate) {
      throw new NotFoundException('Certificate not found');
    }

    return certificate;
  }

  /**
   * Verify certificate
   * Phase 6: Certificate verification page
   */
  async verifyCertificate(certificateNumber: string) {
    const certificate = await this.prisma.certificate.findUnique({
      where: { certificateNumber },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            profilePictureUrl: true,
          },
        },
        template: true,
      },
    });

    if (!certificate) {
      return {
        valid: false,
        message: 'Certificate not found',
      };
    }

    if (certificate.isRevoked) {
      return {
        valid: false,
        message: 'This certificate has been revoked',
        revokedAt: certificate.revokedAt,
        revokedReason: certificate.revokedReason,
      };
    }

    if (certificate.expiryDate && new Date() > certificate.expiryDate) {
      return {
        valid: false,
        message: 'This certificate has expired',
        expiryDate: certificate.expiryDate,
      };
    }

    return {
      valid: true,
      certificate: {
        certificateNumber: certificate.certificateNumber,
        recipientName: certificate.recipientName,
        certificateTitle: certificate.certificateTitle,
        issueDate: certificate.issueDate,
        expiryDate: certificate.expiryDate,
        description: certificate.description,
      },
    };
  }

  /**
   * Get user's certificates
   */
  async getUserCertificates(userId: string, filters?: {
    type?: string;
  }) {
    const where: any = { userId, isRevoked: false };

    if (filters?.type) {
      where.certificateType = filters.type;
    }

    return this.prisma.certificate.findMany({
      where,
      include: {
        template: true,
      },
      orderBy: {
        issueDate: 'desc',
      },
    });
  }

  /**
   * Revoke certificate
   */
  async revoke(id: string, reason: string) {
    return this.prisma.certificate.update({
      where: { id },
      data: {
        isRevoked: true,
        revokedAt: new Date(),
        revokedReason: reason,
      },
    });
  }

  /**
   * Download certificate PDF
   * Phase 6: PDF certificate downloads
   */
  async downloadCertificate(id: string) {
    const certificate = await this.findOne(id);

    if (!certificate.pdfUrl) {
      throw new NotFoundException('Certificate PDF not available');
    }

    return {
      pdfUrl: certificate.pdfUrl,
      filename: `certificate-${certificate.certificateNumber}.pdf`,
    };
  }

  /**
   * Share on LinkedIn
   * Phase 6: LinkedIn certificate sharing
   */
  async getLinkedInShareUrl(id: string) {
    const certificate = await this.findOne(id);

    return {
      shareUrl: certificate.linkedinShareUrl,
      certificateUrl: certificate.verificationUrl,
    };
  }
}
